apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: runasnonroot
spec:
  crd:
    spec:
      names:
        kind: K8sRunAsNonRoot
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package admission
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.securityContext.runAsNonRoot == true
          msg := sprintf("Pod %v does not have runAsNonRoot: true", [input.review.object.metadata.name])
        }