apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  # hostPath удалён – вместо него можно использовать emptyDir или PVC